import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Grid } from "@mui/material";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Footer from "../components/Footer";

const Gallery: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>rocca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container alignItems="center">
          <Grid container md={3} xs={12} pr={2} direction="column">
            <Header />
            <Nav />
            <Footer />
          </Grid>
          <Grid item md={9} xs={12}>
            <Image
              src="/images/slide/slide1.jpg"
              width={1170}
              height={814}
              objectFit="contain"
              alt="slide1"
            />
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Gallery;
