import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Stack, Button, Grid, Paper, styled } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>rocca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container alignItems="center">
          <Grid container md={3} xs={12} pr={2} direction="column">
            <Grid item mb={2}>
              <Image
                src="/images/header/yukino_logo.png"
                width={240}
                height={100}
                objectFit="contain"
                alt="yukino_logo"
              />
            </Grid>
            <Grid item mb={2}>
              copy
            </Grid>
            <Grid item mb={2}>
              test
            </Grid>
            <Grid item mb={2}>
              test
            </Grid>
            <Grid item mb={2}>
              test
            </Grid>
            <Grid item mb={2}>
              test
            </Grid>
            <Grid item mb={2}>
              test
            </Grid>
            <Grid item mb={2}>
              test
            </Grid>
            <Grid item mb={2} fontSize={12} letterSpacing={2}>
              ©︎2022 yukino design works
            </Grid>
          </Grid>
          <Grid item md={9} xs={12}>
            <Image
              src="/images/slide/slide1.jpg"
              width={1170}
              height={812}
              objectFit="contain"
              alt="slide1"
            />
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Home;
